language: node_js

node_js:
  - 11.6.0

cache: npm

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  skip-cleanup: true
  local_dir: build
  on:
    branch: master
  project: "rajananGanesalingam"
